name: i9500_Emergency_Test

on:
  workflow_dispatch:

jobs:
  quick_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Terminal_Selami
        run: |
          echo "Selamunaleykum kanka, sistem ayakta!"
          echo "Islemci Mimarisi:"
          uname -m
          echo "Android 11 Hazirliklari Tamam mi?"
          date
          
      - name: Runner_Hiz_Testi
        run: |
          echo "Su an GitHub sunucusundayiz."
          echo "I9500 icin yol yapiliyor..."
          sleep 5
          echo "Operasyon Basarili: Result GUM!"
