name: i9500 Android 11 Derleyici

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Baslangic
        run: echo "Sistem atesleniyor kanka!"

      - name: Depolama Alani Ac
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /usr/local/lib/android
          df -h

      - name: Sistem Araclarini Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev x11proto-core-dev libx11-dev libgl1-mesa-dev g++-multilib libxml2-utils xsltproc unzip python3 git
